name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Run this workflow only when code is pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # This is the machine type GitHub uses to run the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./Docker/Flask-App
        file: ./Docker/Flask-App/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME}}/flask-app:latest

